document.write('<head>')
    document.write('<title>UCSC ECON 294B</title>')
    document.write('<meta name="description" content="ECON 294B - MS in Applied Economics and Finance Professional Development Seminar" />')
    document.write('<meta name="keywords" content="Eric Aldrich, Eric M. Aldrich, Economics, University of California, Santa Cruz, Eric Mark Aldrich, Aldrich, Eric" />')
    document.write('<link rel="stylesheet" type="text/css" href="'+rootFolder+'style.css" />')
    document.write('<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Varela|News+Cycle|Droid+Serif|Georgia|Oswald:300,400|Open+Sans+Condensed:300,700" />')
    document.write('</head>')
