document.write('<head>')
document.write('<title>Eric Aldrich</title>')
document.write('<meta name="description" content="Homepage for Eric M. Aldrich" />')
document.write('<meta name="keywords" content="Eric Aldrich, Eric M. Aldrich, Economics, University of California, Santa Cruz, Eric Mark Aldrich, Aldrich, Eric" />')
document.write('<link rel="stylesheet" type="text/css" href="'+rootFolder+'style.css" />')
document.write('<link href="https://fonts.googleapis.com/css?family=Varela" rel="stylesheet">')
document.write('</head>')
