document.write('<div class="mainMenu">')
document.write('<div class="name">Eric M. Aldrich</div>')
document.write('<div>')
document.write('<span class="mainMenu"><a class="mainMenu" href="ealdrich.github.io/">HOME</a></span>')
document.write('<span class="mainMenu"><a class="mainMenu" href="ealdrich.github.io/CV/cv.pdf">CV</a></span>')
document.write('<span class="mainMenu"><a class="mainMenu" href="ealdrich.github.io/Teaching/">TEACHING</a></span>')
document.write('<span class="mainMenu"><a class="mainMenu" href="ealdrich.github.io/Research/">RESEARCH</a></span>')
document.write('</div>')
document.write('</div>')
document.write('<div class="banner"></div>')
