document.write('<div class="mainMenu">')
document.write('<div class="name">Eric M. Aldrich</div>')
document.write('<div>')
document.write('<span class="mainMenu"><a class="mainMenu" href="'+rootFolder+'">HOME</a></span>')
document.write('<span class="mainMenu"><a class="mainMenu" href="'+rootFolder+'cv/">CV</a></span>')
document.write('<span class="mainMenu"><a class="mainMenu" href="'+rootFolder+'Teaching/">TEACHING</a></span>')
document.write('<span class="mainMenu"><a class="mainMenu" href="'+rootFolder+'Research/">RESEARCH</a></span>')
document.write('</div>')
document.write('</div>')
document.write('<div class="banner"></div>')
