document.write('<div class="mainMenu">')
    document.write('<div style="padding-top: 15px; text-align: right; padding-right: 10px;">')
    document.write('<span class="mainMenuTitle"><a class="mainMenuTitle" href="ealdrich.github.io/Teaching/Econ133/">ECON 133</a></span>')
    document.write('<span class="mainMenu"><a class="mainMenu" href="ealdrich.github.io/Teaching/Econ133/Syllabus/">Syllabus</a></span>')
    document.write('<span class="mainMenu"><a class="mainMenu" href="ealdrich.github.io/Teaching/Econ133/Slides/">Lecture Notes</a></span>')
    document.write('<span class="mainMenu"><a class="mainMenu" href="ealdrich.github.io/Teaching/Econ133/">Assignments</a></span>')
    document.write('</div>')
    document.write('</div>')
