document.write('<div class="mainMenu">')
    document.write('<div style="padding-top: 15px; text-align: right; padding-right: 10px;">')
    document.write('<span class="mainMenuTitle"><a class="mainMenuTitle" href="'+rootFolder+'">ECON 211C</a></span>')
    document.write('<span class="mainMenu"><a class="mainMenu" href="'+rootFolder+'Syllabus/">Syllabus</a></span>')
    document.write('<span class="mainMenu"><a class="mainMenu" href="'+rootFolder+'LectureNotes/">Lecture Notes</a></span>')
    document.write('<span class="mainMenu"><a class="mainMenu" href="'+rootFolder+'Assignments/">Assignments</a></span>')
    document.write('<span class="mainMenu"><a class="mainMenu" href="'+rootFolder+'Contact/">Contact</a></span>')
    document.write('</div>')
    document.write('</div>')
