document.write('<head>')
    document.write('<title>UCSC CompEcon</title>')
    document.write('<meta name="description" content="Python for Brigham" />')
    document.write('<meta name="keywords" content="Eric Aldrich, Eric M. Aldrich, Economics, University of California, Santa Cruz, Eric Mark Aldrich, Aldrich, Eric" />')
    document.write('<link rel="stylesheet" type="text/css" href="'+rootFolder+'style.css" />')
    document.write('<script type="text/javascript" src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>')
    document.write('<link href="https://fonts.googleapis.com/css?family=News+Cycle|Open+Sans+Condensed:300,700|Oswald:300,400|PT+Serif|Varela" rel="stylesheet">')
    document.write('</head>')
